language: node_js

node_js:  stable

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
        
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm install hexo-cli -g
    - chmod +x ./publish-to-gh-pages.sh  # 为shell文件添加可执行权限

install: npm install
 
script:
    - hexo clean # 清除
    - hexo g # 生成
    
after_script:
    - ./publish-to-gh-pages.sh

branches:
    only:
        - hexo #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
    global:
        - GH_REF: github.com:leeningzzu/leeningzzu.github.io.git #设置GH_REF，注意更改yourname

