# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 李宁的学习笔记
headerTitle: "StatLee on the way"
subtitle: Step by Step
author: StatLee
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url:  https://github.com/leeningzzu/leeningzzu.github.io       # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
rss:  /atom.xml

# Header
menu:
  Home: /
  Archives: /archive
  Categories: /categories
  Tags: /tags
  About: /about
  
#Custom Setting Start

# Site settings
SEOTitle: Knowledge is Power
email: leeningzzu@gmail.com
description: ""
keyword: ""
header-img: img/header_img/home-bg-dark.jpg
signature: true #show signature
signature-img: img/signature/signature-white.png
header-cover: true # make cover the header img
header-cover-color: rgba(0,0,0,.2) # the color cover the header img
img-watermark: 	imageView2/0/q/75|watermark/1/image/aHR0cDovL3BlM29sN3Rqay5ia3QuY2xvdWRkbi5jb20vc2lnbmF0dXJlLXdoaXRlLnBuZw==/dissolve/50/gravity/SouthEast/dx/10/dy/5


# SNS settings
RSS: true
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    leeningzzu
csdn_username:      leeningzzu  
youtube_channel:   channel/UCT6l6ATYtwasn1AyFzD2bSg
email_username:  leeningzzu@163.com
tele_username:  statlee

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# valine
valine: true
valineAppId: vP8YXQlrRR3AJHABL6OpYXjI-gzGzoHsz # your leancloud application appid
valineAppKey: cxMGorRRMXyk1vHXcnjAns8f # your leancloud application appkey
valineNotify: false # mail notifier , https://github.com/xCss/Valine/wiki
valineVerify: false # Verification code
valinePlaceHolder: A disagreement may be the shortest cut between two minds. # comment box placeholder
valineAvatar: hide # gravatar style
valineGuestInfo: nick,mail,link # custom comment header
valinePageSize: 10 # pagination size
visitor: true

# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite

# NeedMoreShare2
# This plugin is a pure javascript sharing lib which is useful in China.
# See: https://github.com/revir/need-more-share2
# Also see: https://github.com/DzmVasileusky/needShareButton
# iconStyle: default | box | light
# boxForm: horizontal | vertical
# position: top / middle / bottom + Left / Center / Right
# networks: Weibo,Wechat,Douban,QQZone,Twitter,Linkedin,Mailto,Reddit,
#           Delicious,StumbleUpon,Pinterest,Facebook,GooglePlus,Slashdot,
#           Technorati,Posterous,Tumblr,GoogleBookmarks,Newsvine,
#           Evernote,Friendfeed,Vkontakte,Odnoklassniki,Mailru
needmoreshare2:
  enable: true
  postbottom: 
    headerEnable: true
    postEnable: true
    enable: true
    options:
      postIconStyle: light
      headerIconStyle: light
      boxForm: horizontal
      postPosition: middleRight
      headerPosition: bottom
      networks: Wechat,Weibo,Douban,Twitter,Facebook,Reddit,Linkedin,Evernote
  float: 
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Wechat,Weibo,Douban,Twitter,Facebook,Reddit,Linkedin,Evernote


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "Just Show Me the Code 👉📜"
sidebar-avatar: img/ironman-draw-1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
post-tags: false                # whether or not using Feature-Tags at bottom of blog page
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

## Category
page_header_category: true # show page_header categories
home_posts_category: true # show posts categories
post-category: false # show page categories at the end
sidebar-category: true # show sidebar categories

## Friends
post-friends: false

friends: [
   {
        title: "白马负金羁",
        href: "https://blog.csdn.net/baimafujinji"
   },{ 
        title: "computer science, math, and statistics",
        href: "https://medium.com/cs-math"
   },{
        title: "Machine Learnings",
        href: "https://machinelearnings.co"
   },{
        title: "深度碎片",
        href: "https://github.com/EmbraceLife"
   },{
        title: "mit-deep-learning",
        href: "https://github.com/lexfridman/mit-deep-learning"
   },{
        title: "Algorithm_Interview_Notes-Chinese",
        href: "https://github.com/imhuay/Algorithm_Interview_Notes-Chinese"     
   }           
 ]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  Software and Skills: Software and Skills
  Programming: Programming
  Theory: Theory
  Algorithm: Algorithm
tag_map:
home_posts_tag: true # show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huweihuang
plugins:
    hexo-generator-feed

#Feed Atom
feed:
    type: atom
    path: atom.xml
    limit: 20

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:leeningzzu/leeningzzu.github.io.git
  #repository: https://github.com/leeningzzu/leeningzzu.github.io
  branch: master
  message: Update CNAME                     
  

